on:
  schedule:
    - cron: "45 03,15 * * *" # Runs at 3:45 AM and 15:45 PM
    - cron: "55 23,1 * * *" # Runs at 3:45 AM and 15:45 PM
    - cron: "30 11,18 * * *" # Runs at 11:00 AM and 6:00 PM

jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Moscow"

    steps:
      - name: Run cleanup trigger
        run: curl -X POST https://liliana-map.onrender.com/trigger-cleanup
