name: First Cron Job

on:
  schedule:
    - cron: '53 15 * * *'  # Runs at 15:42 UTC
    - cron: '42 12 * * *'  # Runs at 12:42 UTC
    - cron: '50 1 * * *'   # Runs at 01:50 UTC
    - cron: '50 7 * * *'   # Runs at 07:50 UTC

jobs:
  cleanup-trigger-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run cleanup trigger 1
        env:
          TZ: "Europe/Moscow"
        run: |
          date
          curl -X POST https://liliana-map.onrender.com/trigger-cleanup

  cleanup-trigger-2:
    runs-on: ubuntu-latest
    steps:
      - name: Run cleanup trigger 2
        env:
          TZ: "Europe/Moscow"
        run: |
          date
          curl -X POST https://liliana-map.onrender.com/trigger-cleanups
