on:
  schedule:
    - cron: "45 03,15 * * *" # Runs at 3:45 AM and 15:45 PM
    - cron: "50 14,18 * * *" # Runs at 11:00 AM and 6:00 PM
    - cron: "50 15,18 * * *" # Runs at 11:00 AM and 6:00 PM
     - cron: "50 12,18 * * *"  # Runs at 11:00 AM and 18:00 PM in UTC
 


jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Moscow"

    steps:
      - name: Run cleanup trigger
        run: curl -X POST https://liliana-map.onrender.com/trigger-cleanup
